workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_pro
    environment:
      android_signing:
        - key1
      groups:
        - sonarqube
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
      node: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          echo $CM_KEYSTORE > $CM_KEYSTORE_PATH         
      - name: Build Android app
        script: |
          ./gradlew assembleRelease  # To generate an .apk use--> ./gradlew bundleRelease
      - name: Generate and upload code analysis report
        script: |
          ./gradlew sonarqube -Dsonar.projectKey=Android -Dsonar.host.url=http://18.237.244.64:9000 -Dsonar.login=da2dba5eaebd637a977797b6a5bfede5531d7294
    artifacts:
      - app/build/outputs/**/**/*.aab
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - kalgi@nevercode.io
      slack:
        channel: '#testing'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false 
