workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_pro
    cache:
      cache_paths:
        - ~/.sonar
    environment:
      android_signing:
        - key1
      groups:
        - sonarqube
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"      
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
      - name: Download and install the SonarScanner
        script: |
          wget -O $FCI_BUILD_DIR/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-macosx.zip
          unzip $FCI_BUILD_DIR/sonar-scanner.zip
          mv sonar-scanner-* sonar-scanner
      - name: Generate and upload code analysis report
        script: |
          export PATH=$PATH:$FCI_BUILD_DIR/sonar-scanner/bin
          sonar-scanner \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.host.url=$SONARQUBE_URL \
          # ./gradlew sonarqube -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONAR_TOKEN
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - kalgi@nevercode.io
      slack:
        channel: '#testing'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false 
