workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_pro
    environment:
      groups:
        - sonarqube
        - keystore_credentials # <-- Includes - FCI_KEYSTORE, FCI_KEYSTORE_PASSWORD, FCI_KEY_PASSWORD, FCI_KEY_ALIAS
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
      node: latest
    cache:
      cache_paths:
        - ~/.sonar
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH         
      - name: Build Android app
        script: |
          ./gradlew bundleRelease  # To generate an .apk use--> ./gradlew assembleRelease
      - name: Generate and upload code analysis report
        script: |
            ./gradlew sonarqube -Dsonar.projectKey=sonar -Dsonar.host.url=http://192.168.29.130:9000 -Dsonar.login=admin -Dsonar.password=admin1
    artifacts:
      - app/build/outputs/**/**/*.aab
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - kalgi@nevercode.io
      slack:
        channel: '#testing'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false 
